name: MSBuild

on:
  push:
    branches-ignore:
      - main
      - Development

env:
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Generate solution with Premake
      run: Solution/external/premake/premake5.exe vs2022

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 Solution/Menyoo.sln -verbosity:minimal
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: MenyooSP
        path: |
          Solution/source/_Build/bin/Release/
          !Solution/source/_Build/bin/Release/Trash/
          !Solution/source/_Build/bin/Release/*.map
